"""Skills API Route — ClawHub Skill Bank: browse, install, and manage agent skills."""

from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter()

# ─── Skill Catalog (extensible marketplace) ────────────────────────

SKILL_CATALOG: list[dict] = [
    # ═══════════════════════════════════════════════════════════════
    # RESEARCH & WEB
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "web-search",
        "name": "Web Search",
        "description": "Busca inteligente na web com DuckDuckGo. Encontra informações atualizadas sobre qualquer tema.",
        "category": "research",
        "icon": "🔍",
        "color": "#06b6d4",
        "author": "Delirium Core",
        "version": "1.2.0",
        "tags": ["web", "search", "research"],
        "compatible_agents": ["orchestrator", "researcher", "analyst", "fullstack", "writer"],
    },
    {
        "id": "web-scraping",
        "name": "Web Scraping",
        "description": "Extrai conteúdo e dados estruturados de qualquer página web com parsing inteligente.",
        "category": "research",
        "icon": "🕷️",
        "color": "#8b5cf6",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["web", "scraping", "data", "extraction"],
        "compatible_agents": ["researcher", "analyst", "developer"],
    },
    {
        "id": "competitive-intel",
        "name": "Competitive Intelligence",
        "description": "Análise de concorrentes, market research, trend spotting e benchmarking.",
        "category": "research",
        "icon": "🔬",
        "color": "#06b6d4",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["research", "competitive", "market", "trends"],
        "compatible_agents": ["researcher", "analyst", "writer"],
    },
    {
        "id": "academic-research",
        "name": "Academic Research",
        "description": "Pesquisa acadêmica: papers, citações, revisão bibliográfica e resumos de artigos científicos.",
        "category": "research",
        "icon": "🎓",
        "color": "#1d4ed8",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["academic", "papers", "citations", "science"],
        "compatible_agents": ["researcher", "analyst", "writer"],
    },
    {
        "id": "news-aggregator",
        "name": "News Aggregator",
        "description": "Agrega e sumariza notícias de múltiplas fontes em tempo real por tema ou região.",
        "category": "research",
        "icon": "📰",
        "color": "#0ea5e9",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["news", "aggregation", "realtime", "media"],
        "compatible_agents": ["researcher", "writer", "orchestrator"],
    },
    {
        "id": "social-media-intel",
        "name": "Social Media Intelligence",
        "description": "Monitora trends, hashtags, engajamento e sentimento em redes sociais.",
        "category": "research",
        "icon": "📱",
        "color": "#e11d48",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["social", "twitter", "instagram", "trends", "sentiment"],
        "compatible_agents": ["researcher", "analyst", "writer"],
    },
    # ═══════════════════════════════════════════════════════════════
    # DEVELOPMENT
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "code-generation",
        "name": "Code Generation",
        "description": "Gera código production-ready em TypeScript, Python, React, Rust, Go e mais de 30 linguagens.",
        "category": "development",
        "icon": "💻",
        "color": "#6366f1",
        "author": "Delirium Core",
        "version": "2.0.0",
        "tags": ["code", "typescript", "python", "react", "rust", "go"],
        "compatible_agents": ["developer", "fullstack", "mobile", "orchestrator"],
    },
    {
        "id": "database-ops",
        "name": "Database Operations",
        "description": "CRUD completo: Supabase, PostgreSQL, MySQL, MongoDB, Redis. Queries, migrações, RLS.",
        "category": "development",
        "icon": "🗄️",
        "color": "#10b981",
        "author": "Delirium Core",
        "version": "1.2.0",
        "tags": ["database", "supabase", "sql", "mongodb", "redis", "crud"],
        "compatible_agents": ["developer", "fullstack", "analyst", "devops"],
    },
    {
        "id": "mobile-app",
        "name": "Mobile App Builder",
        "description": "Cria apps React Native/Expo/Flutter com navegação, gestos, câmera e design nativo.",
        "category": "development",
        "icon": "📱",
        "color": "#3b82f6",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["mobile", "react-native", "expo", "flutter", "ios", "android"],
        "compatible_agents": ["mobile", "fullstack", "developer"],
    },
    {
        "id": "api-design",
        "name": "API Design & Integration",
        "description": "Projeta e implementa APIs RESTful, GraphQL, gRPC, WebSocket com validação e docs automáticos.",
        "category": "development",
        "icon": "🔌",
        "color": "#06b6d4",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["api", "rest", "graphql", "grpc", "websocket", "fastapi"],
        "compatible_agents": ["developer", "fullstack", "devops"],
    },
    {
        "id": "testing-qa",
        "name": "Testing & QA",
        "description": "Testes unitários, integração, e2e, snapshot, load testing com Jest, Vitest, Playwright, Cypress.",
        "category": "development",
        "icon": "🧪",
        "color": "#10b981",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["testing", "jest", "vitest", "playwright", "cypress", "qa"],
        "compatible_agents": ["developer", "fullstack", "devops"],
    },
    {
        "id": "ecommerce-builder",
        "name": "E-Commerce Builder",
        "description": "Cria lojas completas: catálogo, carrinho, checkout, pagamento Stripe/MercadoPago, estoque.",
        "category": "development",
        "icon": "🛒",
        "color": "#f59e0b",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["ecommerce", "store", "stripe", "mercadopago", "cart", "checkout"],
        "compatible_agents": ["fullstack", "designer", "developer"],
    },
    {
        "id": "code-refactor",
        "name": "Code Refactoring",
        "description": "Refatora código: clean code, SOLID, design patterns, performance optimization, debt reduction.",
        "category": "development",
        "icon": "♻️",
        "color": "#22c55e",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["refactor", "clean-code", "solid", "patterns", "optimization"],
        "compatible_agents": ["developer", "fullstack"],
    },
    {
        "id": "code-review",
        "name": "Code Review",
        "description": "Review automatizado: bugs, vulnerabilidades, performance issues, code smells e sugestões de melhoria.",
        "category": "development",
        "icon": "👁️",
        "color": "#a78bfa",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["review", "bugs", "quality", "lint"],
        "compatible_agents": ["developer", "fullstack", "devops"],
    },
    {
        "id": "regex-builder",
        "name": "Regex Builder",
        "description": "Cria, testa e explica expressões regulares complexas com exemplos e edge cases.",
        "category": "development",
        "icon": "🔤",
        "color": "#f472b6",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["regex", "pattern", "matching", "validation"],
        "compatible_agents": ["developer", "fullstack"],
    },
    {
        "id": "realtime-websocket",
        "name": "Real-time & WebSocket",
        "description": "Sistemas real-time: WebSocket, SSE, Supabase Realtime, Socket.IO, pub/sub.",
        "category": "development",
        "icon": "⚡",
        "color": "#facc15",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["realtime", "websocket", "sse", "socket-io", "pubsub"],
        "compatible_agents": ["developer", "fullstack"],
    },
    {
        "id": "auth-system",
        "name": "Auth & Identity",
        "description": "Sistemas de autenticação: OAuth, JWT, RBAC, MFA, social login, SSO, Supabase Auth.",
        "category": "development",
        "icon": "🔐",
        "color": "#7c3aed",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["auth", "oauth", "jwt", "rbac", "mfa", "sso"],
        "compatible_agents": ["developer", "fullstack", "devops"],
    },
    {
        "id": "cms-builder",
        "name": "CMS Builder",
        "description": "Cria sistemas de gerenciamento de conteúdo: WYSIWYG, markdown, media library, drafts.",
        "category": "development",
        "icon": "📝",
        "color": "#2563eb",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["cms", "content", "wysiwyg", "markdown", "admin"],
        "compatible_agents": ["fullstack", "developer"],
    },
    {
        "id": "pwa-builder",
        "name": "PWA Builder",
        "description": "Progressive Web Apps: service worker, offline, push notifications, install prompt.",
        "category": "development",
        "icon": "📲",
        "color": "#0891b2",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["pwa", "offline", "service-worker", "push", "manifest"],
        "compatible_agents": ["fullstack", "developer", "mobile"],
    },
    # ═══════════════════════════════════════════════════════════════
    # DESIGN & UI
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "liquid-glass-design",
        "name": "Liquid Glass Design",
        "description": "Interfaces premium com glassmorphism, gradients, blur effects e animações Apple-tier.",
        "category": "design",
        "icon": "🎨",
        "color": "#ec4899",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["ui", "design", "glassmorphism", "css", "tailwind"],
        "compatible_agents": ["designer", "fullstack", "mobile"],
    },
    {
        "id": "animation-motion",
        "name": "Animation & Motion",
        "description": "Animações premium com Framer Motion, GSAP, Lottie, CSS transitions e micro-interações.",
        "category": "design",
        "icon": "✨",
        "color": "#ec4899",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["animation", "framer-motion", "gsap", "lottie", "transitions"],
        "compatible_agents": ["designer", "fullstack", "mobile"],
    },
    {
        "id": "responsive-layout",
        "name": "Responsive Layout",
        "description": "Layouts responsivos: mobile-first, grid systems, breakpoints, container queries.",
        "category": "design",
        "icon": "📐",
        "color": "#14b8a6",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["responsive", "layout", "grid", "flexbox", "mobile-first"],
        "compatible_agents": ["designer", "fullstack", "mobile"],
    },
    {
        "id": "design-system",
        "name": "Design System",
        "description": "Cria design systems completos: tokens, componentes, variantes, documentação e Storybook.",
        "category": "design",
        "icon": "🧩",
        "color": "#d946ef",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["design-system", "tokens", "components", "storybook"],
        "compatible_agents": ["designer", "fullstack"],
    },
    {
        "id": "icon-svg",
        "name": "Icon & SVG Design",
        "description": "Cria ícones SVG customizados, icon sets, logos e ilustrações vetoriais.",
        "category": "design",
        "icon": "🎯",
        "color": "#f43f5e",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["svg", "icons", "logo", "vector", "illustration"],
        "compatible_agents": ["designer"],
    },
    {
        "id": "dark-mode",
        "name": "Dark Mode & Themes",
        "description": "Implementa dark mode, themes dinâmicos, CSS variables e theme switching.",
        "category": "design",
        "icon": "🌙",
        "color": "#1e293b",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["dark-mode", "themes", "css-variables", "toggle"],
        "compatible_agents": ["designer", "fullstack"],
    },
    {
        "id": "accessibility",
        "name": "Accessibility (a11y)",
        "description": "WCAG compliance: ARIA labels, keyboard navigation, screen readers, contrast ratio.",
        "category": "design",
        "icon": "♿",
        "color": "#0284c7",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["accessibility", "a11y", "wcag", "aria", "keyboard"],
        "compatible_agents": ["designer", "fullstack", "developer"],
    },
    # ═══════════════════════════════════════════════════════════════
    # DEVOPS & INFRASTRUCTURE
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "git-ops",
        "name": "Git & GitHub",
        "description": "Controle de versão: commit, push, PR, issues, branches, merge strategies, git flow.",
        "category": "devops",
        "icon": "📦",
        "color": "#f59e0b",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["git", "github", "version-control", "branches", "pr"],
        "compatible_agents": ["developer", "devops", "fullstack"],
    },
    {
        "id": "docker-deploy",
        "name": "Docker & Containers",
        "description": "Containerização: Dockerfile, docker-compose, multi-stage builds, registries.",
        "category": "devops",
        "icon": "🐳",
        "color": "#3b82f6",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["docker", "container", "dockerfile", "compose"],
        "compatible_agents": ["devops", "developer", "fullstack"],
    },
    {
        "id": "ci-cd-pipeline",
        "name": "CI/CD Pipeline",
        "description": "Pipelines de deploy: GitHub Actions, GitLab CI, Vercel, Railway, Netlify auto-deploy.",
        "category": "devops",
        "icon": "🚀",
        "color": "#16a34a",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["ci-cd", "github-actions", "deploy", "vercel", "railway"],
        "compatible_agents": ["devops", "developer"],
    },
    {
        "id": "cloud-infra",
        "name": "Cloud Infrastructure",
        "description": "AWS, GCP, Azure, DigitalOcean: compute, storage, CDN, DNS, load balancers.",
        "category": "devops",
        "icon": "☁️",
        "color": "#f97316",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["aws", "gcp", "azure", "cloud", "infrastructure"],
        "compatible_agents": ["devops"],
    },
    {
        "id": "monitoring-logging",
        "name": "Monitoring & Logging",
        "description": "Observabilidade: logs, métricas, alertas, health checks, Sentry, Datadog, Grafana.",
        "category": "devops",
        "icon": "📡",
        "color": "#dc2626",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["monitoring", "logging", "sentry", "metrics", "alerts"],
        "compatible_agents": ["devops", "developer"],
    },
    {
        "id": "nginx-caddy",
        "name": "Reverse Proxy & SSL",
        "description": "Configura Nginx, Caddy, Traefik: reverse proxy, SSL/TLS, rate limiting, caching.",
        "category": "devops",
        "icon": "🔀",
        "color": "#059669",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["nginx", "caddy", "ssl", "proxy", "traefik"],
        "compatible_agents": ["devops"],
    },
    # ═══════════════════════════════════════════════════════════════
    # SECURITY
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "security-audit",
        "name": "Security Audit",
        "description": "Auditoria OWASP Top 10, RLS, headers, CSP, XSS, CSRF, SQL injection, rate limiting.",
        "category": "security",
        "icon": "🛡️",
        "color": "#ef4444",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["security", "owasp", "audit", "rls", "xss", "csrf"],
        "compatible_agents": ["developer", "devops", "fullstack"],
    },
    {
        "id": "encryption-crypto",
        "name": "Encryption & Crypto",
        "description": "Criptografia: hashing, AES, RSA, tokens, key management, secure storage.",
        "category": "security",
        "icon": "🔒",
        "color": "#b91c1c",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["encryption", "crypto", "hashing", "aes", "rsa"],
        "compatible_agents": ["developer", "devops"],
    },
    {
        "id": "pentest-scanner",
        "name": "Vulnerability Scanner",
        "description": "Scan de vulnerabilidades: dependency audit, secret detection, SAST, DAST.",
        "category": "security",
        "icon": "🔓",
        "color": "#991b1b",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["pentest", "vulnerability", "scan", "dependency-audit"],
        "compatible_agents": ["devops", "developer"],
    },
    # ═══════════════════════════════════════════════════════════════
    # CONTENT & WRITING
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "seo-copywriting",
        "name": "SEO & Copywriting",
        "description": "Conteúdo otimizado para SEO, copy persuasiva, headlines, meta tags e microcopy.",
        "category": "content",
        "icon": "✍️",
        "color": "#a855f7",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["seo", "copywriting", "content", "marketing", "meta"],
        "compatible_agents": ["writer", "researcher", "orchestrator"],
    },
    {
        "id": "translation",
        "name": "Multi-language Translation",
        "description": "Tradução profissional em 50+ idiomas com contexto e tom correto, i18n para apps.",
        "category": "content",
        "icon": "🌐",
        "color": "#0ea5e9",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["translation", "i18n", "multilingual", "localization"],
        "compatible_agents": ["writer", "orchestrator", "fullstack"],
    },
    {
        "id": "documentation",
        "name": "Technical Documentation",
        "description": "Docs técnicos: README, API docs, guides, changelogs, Swagger/OpenAPI, JSDoc.",
        "category": "content",
        "icon": "📚",
        "color": "#6d28d9",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["docs", "readme", "api-docs", "swagger", "jsdoc"],
        "compatible_agents": ["writer", "developer", "fullstack"],
    },
    {
        "id": "email-templates",
        "name": "Email Templates",
        "description": "Cria templates de email responsivos: transacional, marketing, newsletter com MJML.",
        "category": "content",
        "icon": "📧",
        "color": "#8b5cf6",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["email", "template", "newsletter", "mjml", "marketing"],
        "compatible_agents": ["writer", "designer", "fullstack"],
    },
    {
        "id": "blog-writer",
        "name": "Blog & Article Writer",
        "description": "Escreve artigos, posts de blog, threads e conteúdo longo com SEO e storytelling.",
        "category": "content",
        "icon": "📝",
        "color": "#7c3aed",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["blog", "article", "writing", "storytelling"],
        "compatible_agents": ["writer", "researcher"],
    },
    {
        "id": "social-content",
        "name": "Social Media Content",
        "description": "Cria posts, captions, hashtags e calendário editorial para redes sociais.",
        "category": "content",
        "icon": "💬",
        "color": "#e11d48",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["social", "posts", "captions", "hashtags", "calendar"],
        "compatible_agents": ["writer"],
    },
    # ═══════════════════════════════════════════════════════════════
    # ANALYTICS & DATA
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "data-analysis",
        "name": "Data Analysis",
        "description": "Análise de dados com pandas, numpy, métricas, KPIs, relatórios e dashboards.",
        "category": "analytics",
        "icon": "📊",
        "color": "#f97316",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["data", "pandas", "numpy", "analysis", "metrics", "kpi"],
        "compatible_agents": ["analyst", "researcher", "developer"],
    },
    {
        "id": "data-visualization",
        "name": "Data Visualization",
        "description": "Gráficos e dashboards: Chart.js, D3.js, Recharts, Plotly, mapas de calor, geo.",
        "category": "analytics",
        "icon": "📈",
        "color": "#ea580c",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["charts", "d3", "recharts", "plotly", "dashboard"],
        "compatible_agents": ["analyst", "designer", "fullstack"],
    },
    {
        "id": "spreadsheet-ops",
        "name": "Spreadsheet Operations",
        "description": "Manipula CSV, Excel, Google Sheets: parsing, transformação, pivot tables, fórmulas.",
        "category": "analytics",
        "icon": "📋",
        "color": "#16a34a",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["csv", "excel", "sheets", "pivot", "formulas"],
        "compatible_agents": ["analyst", "researcher"],
    },
    {
        "id": "financial-analysis",
        "name": "Financial Analysis",
        "description": "Análise financeira: projeções, valuation, ROI, fluxo de caixa, relatórios contábeis.",
        "category": "analytics",
        "icon": "💰",
        "color": "#059669",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["finance", "roi", "valuation", "cashflow", "accounting"],
        "compatible_agents": ["analyst"],
    },
    {
        "id": "statistics",
        "name": "Statistics & ML Basics",
        "description": "Estatística, regressão, classificação, clustering, A/B testing, scikit-learn basics.",
        "category": "analytics",
        "icon": "🧮",
        "color": "#7c3aed",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["statistics", "ml", "regression", "classification", "ab-testing"],
        "compatible_agents": ["analyst", "researcher", "developer"],
    },
    # ═══════════════════════════════════════════════════════════════
    # MEDIA & CREATIVE
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "voice-tts-stt",
        "name": "Voice & Speech",
        "description": "Text-to-Speech e Speech-to-Text com Edge TTS, ElevenLabs, OpenAI Whisper e Groq.",
        "category": "media",
        "icon": "🎙️",
        "color": "#ef4444",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["voice", "tts", "stt", "speech", "whisper"],
        "compatible_agents": ["orchestrator", "fullstack"],
    },
    {
        "id": "image-generation",
        "name": "Image Generation",
        "description": "Gera imagens com DALL-E, Stable Diffusion, Midjourney, Flux. Prompts otimizados.",
        "category": "media",
        "icon": "🖼️",
        "color": "#a855f7",
        "author": "Delirium Core",
        "version": "1.1.0",
        "tags": ["image", "dalle", "stable-diffusion", "midjourney", "flux"],
        "compatible_agents": ["designer", "writer", "orchestrator"],
    },
    {
        "id": "video-editing",
        "name": "Video Processing",
        "description": "Processamento de vídeo: ffmpeg, thumbnail gen, transcrição, legendas automáticas.",
        "category": "media",
        "icon": "🎬",
        "color": "#dc2626",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["video", "ffmpeg", "transcription", "subtitles", "thumbnail"],
        "compatible_agents": ["designer", "orchestrator"],
    },
    {
        "id": "audio-processing",
        "name": "Audio Processing",
        "description": "Manipulação de áudio: conversão, noise removal, concatenação, podcast editing.",
        "category": "media",
        "icon": "🎵",
        "color": "#9333ea",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["audio", "podcast", "noise-removal", "conversion"],
        "compatible_agents": ["orchestrator"],
    },
    {
        "id": "pdf-processor",
        "name": "PDF Processor",
        "description": "Lê, extrai, gera e manipula PDFs: merge, split, OCR, formulários, assinaturas.",
        "category": "media",
        "icon": "📄",
        "color": "#dc2626",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["pdf", "ocr", "merge", "split", "forms"],
        "compatible_agents": ["analyst", "writer", "orchestrator"],
    },
    {
        "id": "qr-barcode",
        "name": "QR Code & Barcode",
        "description": "Gera e decodifica QR codes, barcodes, data matrix para apps e marketing.",
        "category": "media",
        "icon": "📷",
        "color": "#1e293b",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["qr", "barcode", "generator", "scanner"],
        "compatible_agents": ["developer", "fullstack", "designer"],
    },
    # ═══════════════════════════════════════════════════════════════
    # AI & MACHINE LEARNING
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "prompt-engineering",
        "name": "Prompt Engineering",
        "description": "Otimiza prompts para LLMs: chain-of-thought, few-shot, system prompts, RAG patterns.",
        "category": "ai",
        "icon": "🧠",
        "color": "#8b5cf6",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["prompt", "llm", "cot", "few-shot", "rag"],
        "compatible_agents": ["orchestrator", "researcher", "developer"],
    },
    {
        "id": "embeddings-vectordb",
        "name": "Embeddings & Vector DB",
        "description": "Embeddings, vector search, RAG pipelines com Pinecone, Supabase pgvector, Chroma.",
        "category": "ai",
        "icon": "🔮",
        "color": "#7c3aed",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["embeddings", "vector", "rag", "pinecone", "pgvector"],
        "compatible_agents": ["developer", "researcher"],
    },
    {
        "id": "nlp-text",
        "name": "NLP & Text Processing",
        "description": "Processamento de linguagem: sentiment analysis, NER, summarization, classification.",
        "category": "ai",
        "icon": "🗣️",
        "color": "#6366f1",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["nlp", "sentiment", "ner", "summarization", "classification"],
        "compatible_agents": ["researcher", "analyst", "developer"],
    },
    {
        "id": "agent-builder",
        "name": "AI Agent Builder",
        "description": "Cria agentes personalizados: tool use, memory, multi-step reasoning, function calling.",
        "category": "ai",
        "icon": "🤖",
        "color": "#4f46e5",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["agent", "tools", "function-calling", "reasoning"],
        "compatible_agents": ["orchestrator", "developer"],
    },
    {
        "id": "fine-tuning",
        "name": "Model Fine-tuning",
        "description": "Fine-tune de modelos: dataset preparation, LoRA, RLHF, evaluation, deployment.",
        "category": "ai",
        "icon": "⚙️",
        "color": "#3730a3",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["fine-tuning", "lora", "rlhf", "training", "dataset"],
        "compatible_agents": ["researcher", "developer"],
    },
    # ═══════════════════════════════════════════════════════════════
    # AUTOMATION & WORKFLOW
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "task-automation",
        "name": "Task Automation",
        "description": "Automatiza tarefas repetitivas: file ops, cron jobs, data pipelines, batch processing.",
        "category": "automation",
        "icon": "⚡",
        "color": "#eab308",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["automation", "cron", "pipeline", "batch", "scripting"],
        "compatible_agents": ["devops", "developer", "orchestrator"],
    },
    {
        "id": "workflow-builder",
        "name": "Workflow Builder",
        "description": "Cria workflows multi-step: n8n, Zapier-style, event-driven, state machines.",
        "category": "automation",
        "icon": "🔄",
        "color": "#f59e0b",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["workflow", "n8n", "zapier", "event-driven", "state-machine"],
        "compatible_agents": ["orchestrator", "devops", "developer"],
    },
    {
        "id": "notification-system",
        "name": "Notification System",
        "description": "Push notifications, email alerts, SMS, webhook, Slack/Discord/Telegram bots.",
        "category": "automation",
        "icon": "🔔",
        "color": "#f97316",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["notification", "push", "email", "sms", "webhook", "bot"],
        "compatible_agents": ["developer", "fullstack", "devops"],
    },
    {
        "id": "scheduler",
        "name": "Task Scheduler",
        "description": "Agendamento de tarefas: cron expressions, queue management, retry logic, dead-letter.",
        "category": "automation",
        "icon": "⏰",
        "color": "#0891b2",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["scheduler", "cron", "queue", "retry", "jobs"],
        "compatible_agents": ["devops", "developer"],
    },
    {
        "id": "web-automation",
        "name": "Web Automation",
        "description": "Automação web: Puppeteer, Playwright, form filling, screenshots, scraping avançado.",
        "category": "automation",
        "icon": "🌐",
        "color": "#4f46e5",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["puppeteer", "playwright", "browser", "scraping", "automation"],
        "compatible_agents": ["developer", "researcher", "devops"],
    },
    # ═══════════════════════════════════════════════════════════════
    # BUSINESS & PRODUCTIVITY
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "project-management",
        "name": "Project Management",
        "description": "Gestão de projetos: sprints, kanban, milestones, burndown, Jira/Linear/Notion integration.",
        "category": "business",
        "icon": "📋",
        "color": "#2563eb",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["project", "sprint", "kanban", "jira", "management"],
        "compatible_agents": ["orchestrator", "analyst"],
    },
    {
        "id": "pitch-deck",
        "name": "Pitch Deck & Presentations",
        "description": "Cria pitch decks, apresentações e slides persuasivos com storytelling e dados.",
        "category": "business",
        "icon": "🎤",
        "color": "#7c3aed",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["pitch", "presentation", "slides", "startup", "investor"],
        "compatible_agents": ["writer", "analyst"],
    },
    {
        "id": "legal-contracts",
        "name": "Legal & Contracts",
        "description": "Gera e revisa contratos, termos de uso, privacy policy, NDA, LGPD compliance.",
        "category": "business",
        "icon": "⚖️",
        "color": "#4b5563",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["legal", "contracts", "privacy", "lgpd", "terms"],
        "compatible_agents": ["writer", "analyst"],
    },
    {
        "id": "invoice-finance",
        "name": "Invoice & Billing",
        "description": "Gera invoices, recibos, relatórios financeiros, integração com gateways de pagamento.",
        "category": "business",
        "icon": "🧾",
        "color": "#059669",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["invoice", "billing", "receipt", "payment", "finance"],
        "compatible_agents": ["analyst", "fullstack"],
    },
    {
        "id": "crm-builder",
        "name": "CRM Builder",
        "description": "Cria sistemas CRM: contacts, deals, pipeline, follow-ups, automações de vendas.",
        "category": "business",
        "icon": "🤝",
        "color": "#0d9488",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["crm", "sales", "contacts", "pipeline", "deals"],
        "compatible_agents": ["fullstack", "developer"],
    },
    {
        "id": "calendar-scheduling",
        "name": "Calendar & Scheduling",
        "description": "Integração com calendários: agendamento, disponibilidade, booking, reminders.",
        "category": "business",
        "icon": "📅",
        "color": "#0284c7",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["calendar", "scheduling", "booking", "reminders"],
        "compatible_agents": ["orchestrator", "fullstack"],
    },
    # ═══════════════════════════════════════════════════════════════
    # MATH & SCIENCE
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "math-solver",
        "name": "Math Solver",
        "description": "Resolve equações, cálculo, álgebra linear, otimização, LaTeX rendering.",
        "category": "science",
        "icon": "🔢",
        "color": "#6366f1",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["math", "equations", "calculus", "algebra", "latex"],
        "compatible_agents": ["analyst", "researcher"],
    },
    {
        "id": "weather-geo",
        "name": "Weather & Geolocation",
        "description": "Dados de clima em tempo real, previsões, geocoding, mapas e coordenadas.",
        "category": "science",
        "icon": "🌤️",
        "color": "#0ea5e9",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["weather", "geo", "maps", "coordinates", "api"],
        "compatible_agents": ["researcher", "orchestrator"],
    },
    {
        "id": "unit-converter",
        "name": "Unit Converter",
        "description": "Converte unidades: moedas, medidas, timestamps, timezones, encodings.",
        "category": "science",
        "icon": "⚖️",
        "color": "#14b8a6",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["converter", "units", "currency", "timezone", "encoding"],
        "compatible_agents": ["orchestrator", "analyst"],
    },
    # ═══════════════════════════════════════════════════════════════
    # MCP & INTEGRATIONS
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "mcp-server",
        "name": "MCP Server Builder",
        "description": "Cria e gerencia MCP servers: tool definitions, transport, auth, resource management.",
        "category": "integrations",
        "icon": "🔗",
        "color": "#4f46e5",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["mcp", "server", "tools", "protocol", "integration"],
        "compatible_agents": ["developer", "orchestrator"],
    },
    {
        "id": "webhook-manager",
        "name": "Webhook Manager",
        "description": "Gerencia webhooks: incoming/outgoing, signature verification, retry, logging.",
        "category": "integrations",
        "icon": "🪝",
        "color": "#0891b2",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["webhook", "http", "signature", "events"],
        "compatible_agents": ["developer", "devops"],
    },
    {
        "id": "oauth-connector",
        "name": "OAuth Connector",
        "description": "Conecta com 50+ serviços via OAuth: Google, GitHub, Slack, Discord, Notion, Spotify.",
        "category": "integrations",
        "icon": "🔑",
        "color": "#f59e0b",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["oauth", "google", "github", "slack", "discord", "notion"],
        "compatible_agents": ["developer", "fullstack", "orchestrator"],
    },
    {
        "id": "stripe-payments",
        "name": "Stripe Payments",
        "description": "Integração Stripe: checkout, subscriptions, invoices, webhooks, customer portal.",
        "category": "integrations",
        "icon": "💳",
        "color": "#6366f1",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["stripe", "payments", "subscription", "checkout", "billing"],
        "compatible_agents": ["fullstack", "developer"],
    },
    {
        "id": "supabase-advanced",
        "name": "Supabase Advanced",
        "description": "Supabase pro: Edge Functions, Realtime, Storage, Row Level Security, triggers, RPCs.",
        "category": "integrations",
        "icon": "⚡",
        "color": "#10b981",
        "author": "Delirium Core",
        "version": "1.0.0",
        "tags": ["supabase", "edge-functions", "realtime", "storage", "rls"],
        "compatible_agents": ["developer", "fullstack", "devops"],
    },
]

# In-memory installed skills per agent
_installed_skills: dict[str, set[str]] = {}

# All agents start with their default skills installed
_DEFAULT_SKILLS: dict[str, list[str]] = {
    "orchestrator": [
        "web-search", "code-generation", "voice-tts-stt", "prompt-engineering",
        "task-automation", "workflow-builder", "translation", "project-management",
        "calendar-scheduling", "news-aggregator",
    ],
    "designer": [
        "liquid-glass-design", "animation-motion", "image-generation", "responsive-layout",
        "design-system", "icon-svg", "dark-mode", "accessibility", "video-editing",
    ],
    "developer": [
        "code-generation", "database-ops", "git-ops", "api-design", "testing-qa",
        "code-refactor", "code-review", "regex-builder", "realtime-websocket",
        "auth-system", "mcp-server",
    ],
    "fullstack": [
        "code-generation", "liquid-glass-design", "database-ops", "ecommerce-builder",
        "mobile-app", "api-design", "auth-system", "pwa-builder", "cms-builder",
        "stripe-payments", "supabase-advanced", "notification-system",
    ],
    "researcher": [
        "web-search", "web-scraping", "competitive-intel", "data-analysis",
        "academic-research", "news-aggregator", "social-media-intel",
        "nlp-text", "statistics",
    ],
    "analyst": [
        "data-analysis", "web-search", "database-ops", "data-visualization",
        "spreadsheet-ops", "financial-analysis", "statistics", "math-solver",
    ],
    "writer": [
        "seo-copywriting", "web-search", "translation", "documentation",
        "email-templates", "blog-writer", "social-content", "image-generation",
    ],
    "devops": [
        "docker-deploy", "git-ops", "security-audit", "ci-cd-pipeline",
        "cloud-infra", "monitoring-logging", "nginx-caddy", "task-automation",
        "scheduler", "pentest-scanner",
    ],
    "mobile": [
        "mobile-app", "code-generation", "liquid-glass-design", "pwa-builder",
        "animation-motion", "responsive-layout", "auth-system",
    ],
}

def _get_agent_skills(agent_id: str) -> set[str]:
    if agent_id not in _installed_skills:
        defaults = _DEFAULT_SKILLS.get(agent_id, [])
        _installed_skills[agent_id] = set(defaults)
    return _installed_skills[agent_id]


class SkillInstall(BaseModel):
    agent_id: str


@router.get("")
@router.get("/")
async def list_skills(category: str | None = None) -> list[dict]:
    """List all available skills in the ClawHub catalog."""
    skills = []
    for skill in SKILL_CATALOG:
        data = {**skill, "install_count": sum(1 for a in _installed_skills.values() if skill["id"] in a) + sum(1 for a, defaults in _DEFAULT_SKILLS.items() if skill["id"] in defaults and a not in _installed_skills)}
        if category and skill["category"] != category:
            continue
        skills.append(data)
    return skills


@router.get("/categories")
async def list_skill_categories() -> list[dict]:
    """List all skill categories with counts."""
    cat_counts: dict[str, int] = {}
    for skill in SKILL_CATALOG:
        cat = skill["category"]
        cat_counts[cat] = cat_counts.get(cat, 0) + 1
    return [{"id": k, "count": v} for k, v in sorted(cat_counts.items())]


@router.get("/installed/{agent_id}")
async def get_installed_skills(agent_id: str) -> list[dict]:
    """Get skills installed for a specific agent."""
    installed = _get_agent_skills(agent_id)
    return [s for s in SKILL_CATALOG if s["id"] in installed]


@router.post("/{skill_id}/install")
async def install_skill(skill_id: str, body: SkillInstall) -> dict:
    """Install a skill for an agent."""
    skill = next((s for s in SKILL_CATALOG if s["id"] == skill_id), None)
    if not skill:
        return {"error": "Skill not found"}
    if body.agent_id not in skill["compatible_agents"]:
        return {"error": f"Skill not compatible with agent '{body.agent_id}'"}
    skills = _get_agent_skills(body.agent_id)
    skills.add(skill_id)
    return {"status": "installed", "skill_id": skill_id, "agent_id": body.agent_id}


@router.post("/{skill_id}/uninstall")
async def uninstall_skill(skill_id: str, body: SkillInstall) -> dict:
    """Uninstall a skill from an agent."""
    skills = _get_agent_skills(body.agent_id)
    skills.discard(skill_id)
    return {"status": "uninstalled", "skill_id": skill_id, "agent_id": body.agent_id}


@router.get("/{skill_id}")
async def get_skill(skill_id: str) -> dict:
    """Get details for a specific skill."""
    skill = next((s for s in SKILL_CATALOG if s["id"] == skill_id), None)
    if not skill:
        return {"error": "Skill not found"}
    return {
        **skill,
        "installed_by": [a for a, skills in _installed_skills.items() if skill_id in skills] + [a for a, defaults in _DEFAULT_SKILLS.items() if skill_id in defaults and a not in _installed_skills],
    }
